---
- name: Configure web server

  hosts: webservers
  
  become: true

  tasks:
    - name: Check if certbot can get certificates
      command: certbot renew --dry-run
      register: certbot_output
      ignore_errors: yes

    - name: Echo certbot command output
      debug:
        var: certbot_output.stdout_lines